# Generated by Django 5.1.2 on 2024-10-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sobrenome'),
        ),
    ]
