# Generated by Django 5.1.2 on 2024-10-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('theme', models.CharField(choices=[('none', 'Sem tema especifico'), ('Hallowen', 'Tema de hallowen'), ('Natal', 'Tema de Natal'), ('AnoNovo', 'Tema de Ano novo')], default='none', max_length=30, verbose_name='Tema')),
                ('shot_description', models.TextField(max_length=255, verbose_name='Descrição curta')),
                ('long_description', models.TextField(verbose_name='Descrição longa')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_image/%Y/%m/%d/', verbose_name='Imagem')),
                ('slug', models.SlugField(unique=True, verbose_name='Código')),
                ('marketing_price', models.FloatField(default=0, verbose_name='Preço')),
                ('promotional_price', models.FloatField(default=0, verbose_name='Preço promocional')),
                ('type', models.CharField(choices=[('Aberto', 'Pack com imagens separadas'), ('Fechado', 'Pack com imagens Finalizadas')], default='Aberto', max_length=30, verbose_name='Tipo')),
                ('stockPerPurchase', models.IntegerField(default=10, verbose_name='Quantidade de downloads por compra')),
            ],
        ),
    ]
