# Generated by Django 5.1.2 on 2024-10-13 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'produto', 'verbose_name_plural': 'produtos'},
        ),
        migrations.AlterField(
            model_name='product',
            name='stockPerPurchase',
            field=models.PositiveIntegerField(default=10, verbose_name='Quantidade de downloads por compra'),
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('price', models.FloatField(verbose_name='Preço')),
                ('promotional_price_variation', models.FloatField(default=0, verbose_name='Preço Promocional')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='Estoque')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'VAriação',
                'verbose_name_plural': 'Variações',
            },
        ),
    ]
